spring.application.name=url-shortener

# Database (H2 In-Memory)
spring.datasource.url=jdbc:h2:mem:urldb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=password
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update

# H2 Console (for debugging)
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Redis Config (Default Localhost)
spring.data.redis.host=localhost
spring.data.redis.port=6379

# Server
server.port=8080
